import { Component, OnInit } from '@angular/core';
import { NavController } from '@ionic/angular';

@Component({
  selector: 'app-emergency-call-reg',
  templateUrl: './emergency-call-reg.page.html',
  styleUrls: ['./emergency-call-reg.page.scss'],
})
export class EmergencyCallRegPage implements OnInit {
  loading;
  emergency_call_data = [
    {
      id: '1799',
      lat: '0',
      lon: '0',
      village_id: '16232',
      taluk_id: '',
      district_id: '29',
      reference_num: 'YwMUO0',
      date_time_entry: '2021-12-01 08:02:24',
      status: 'call forwarded',
      caller_name: 'Public ',
      address: 'Sundankurichi ',
      Phone_Number: '0',
      email: null,
      caller_category: 'Public',
      category: 'Water Problem',
      sub_category: 'River Bank/Canal Breach',
      message:
        'சுண்டங்குறிச்சி கிராமத்தில் ஓடை ஆக்கிரமிப்பு  செய்யப்பட்டு ஓராண்டு நிறைவடைந்த நிலையிலும்  நடவடிக்கை எடுக்காததால் தண்ணீர் தேங்கி விவசாயத்திற்கு கேடு வைக்கிறது. வட்டாட்சியர் பலமுறை பார்த்து சென்றும் எவ்வித நடவடிக்கையும் இல்லை.',
      district_name: null,
      source: 'App',
      remarks: '',
      call_forward_to: 'drotnv@nic.in',
      date_time_status_entry: '2021-12-11 00:01:10',
      staff_name: '',
      staff_contact: '0',
      staff_department: '',
      staff_details: 'Collector',
      action_details: '',
      log: 'email sent success to eoctirunelveli@gmail.com',
      image_1: 'No Image',
      image_2: '',
      timestamp: null,
      img1_link_org: 'No Image',
      img2_link_org: 'No Image',
      reply_updated_by: '',
      reply_remarks: '',
      reply_updated_on: '2024-10-15 20:18:34',
      user_id: null,
    },
    {
      id: '1665',
      lat: '0',
      lon: '0',
      village_id: '16232',
      taluk_id: '',
      district_id: '29',
      reference_num: 'VoonTN',
      date_time_entry: '2021-11-19 12:36:35',
      status: 'rejected',
      caller_name: 'Publick',
      address: 'Panneerooth ',
      Phone_Number: '0',
      email: null,
      caller_category: 'Public',
      category: 'General',
      sub_category: 'Others',
      message:
        'Sundankurichi village survey number 112 government promboke oodai fully encroached. Till time no actions were taken by concerned department. In this regard two mens were quarrel this land encroachment and one was admitted in government hospital tirunelveli.',
      district_name: null,
      source: 'App',
      remarks: '',
      call_forward_to: 'drotnv@nic.in',
      date_time_status_entry: '2021-11-29 00:03:27',
      staff_name: '',
      staff_contact: '0',
      staff_department: '15',
      staff_details: 'Collector',
      action_details: '',
      log: 'email sent success to eoctirunelveli@gmail.com',
      image_1: 'No Image',
      image_2: '',
      timestamp: null,
      img1_link_org: 'No Image',
      img2_link_org: 'No Image',
      reply_updated_by: '',
      reply_remarks: 'Encroachment removed',
      reply_updated_on: '2024-10-15 20:18:34',
      user_id: '48',
    },
    {
      id: '1664',
      lat: null,
      lon: null,
      village_id: '16232',
      taluk_id: '',
      district_id: '29',
      reference_num: 'NojkC',
      date_time_entry: '2021-11-19 00:21:26',
      status: 'action taken',
      caller_name: 'பொதுமக்கள்',
      address: 'பன்னீா்ஊத்து',
      Phone_Number: '0',
      email: '',
      caller_category: 'Public',
      category: 'General',
      sub_category: 'Others',
      message:
        'பன்னீருத்து கிராமம் பொிய குளத்திற்கு தண்ணீா் ஓடையினை சா்வே நம்பா் 112 சுண்டங்குறிச்சி கிராமத்தினா் ஆக்கிரமிப்பு செய்துள்ளனா். இது வரை நடவடிக்கை எடுக்கப்படவில்லை.',
      district_name: null,
      source: 'web',
      remarks: '',
      call_forward_to: 'drotnv@nic.in',
      date_time_status_entry: '2021-11-29 00:03:21',
      staff_name: '',
      staff_contact: '0',
      staff_department: '',
      staff_details: 'Collector',
      action_details: '',
      log: 'email sent success to eoctirunelveli@gmail.com',
      image_1: '137ef89427c600fe58272aee4203dd33.jpg',
      image_2: null,
      timestamp: null,
      img1_link_org: null,
      img2_link_org: null,
      reply_updated_by: '',
      reply_remarks: 'Encroachment removed',
      reply_updated_on: '2024-10-15 20:18:34',
      user_id: '48',
    },
    {
      id: '336',
      lat: '11.2336',
      lon: '78.8813',
      village_id: '0',
      taluk_id: '',
      district_id: '0',
      reference_num: '',
      date_time_entry: '2019-10-29 10:00:00',
      status: 'action taken',
      caller_name: 'Asaithambi S',
      address:
        'Nallarikkai village, kunnam taluk, Perambalur, Tamil Nadu 621212, India',
      Phone_Number: '0',
      email: '',
      caller_category: '',
      category: '0',
      sub_category: 'Wall or House collapse',
      message: '\n\tTiled damage\n',
      district_name: null,
      source: 'App',
      remarks: '\n\tnil\n',
      call_forward_to: '',
      date_time_status_entry: '2019-01-11 00:00:00',
      staff_name: '',
      staff_contact: '0',
      staff_department: '',
      staff_details: 'DM Tahsildar',
      action_details:
        '\n\tஇப்புகாா் தொடா்பாக பயனாளிக்கு நிவாரணம் வழங்கப்பட்டுவிட்டது.\n',
      log: '',
      image_1: null,
      image_2: null,
      timestamp: '31-10-2019 08:12:48 PM ',
      img1_link_org:
        'http://beta-tnsmart.rimes.int/DATA/Report_Emergency_Images/9943355277_31_10_2019_081248_image1.png',
      img2_link_org:
        'http://beta-tnsmart.rimes.int/DATA/Report_Emergency_Images/9943355277_31_10_2019_081248_image2.png',
      reply_updated_by: '',
      reply_remarks: '',
      reply_updated_on: '2021-11-09 14:21:27',
      user_id: null,
    },
    {
      id: '275',
      lat: '12.9967',
      lon: '80.2634',
      village_id: '0',
      taluk_id: '',
      district_id: '0',
      reference_num: '',
      date_time_entry: '2019-09-22 10:30:00',
      status: 'action taken',
      caller_name: 'tamilselvi',
      address: '722,31st cross street T.P.Chatramchennai 600030',
      Phone_Number: '0',
      email: '',
      caller_category: '',
      category: '0',
      sub_category: 'Overflow of Water bodies',
      message: '\n\tdrainage blocked overflow going on home.\n',
      district_name: null,
      source: '',
      remarks: '\n\tpls take acction immediately sir thank you\n',
      call_forward_to: '',
      date_time_status_entry: '2019-01-11 00:00:00',
      staff_name: '',
      staff_contact: '0',
      staff_department: '',
      staff_details: 'DM Tahsildar',
      action_details: '',
      log: 'email sent success to gcccontrolroom@gmail.com',
      image_1: null,
      image_2: null,
      timestamp: null,
      img1_link_org: null,
      img2_link_org: null,
      reply_updated_by: '',
      reply_remarks: '',
      reply_updated_on: '2021-07-30 17:35:47',
      user_id: null,
    },
  ];

  constructor(private navCtrl: NavController) {}

  ngOnInit() {}

  respond(call) {
    // alert('hi');
    this.navCtrl.navigateForward('emergency-call-reg/respond', {
      state: { param: [call] },
    });
  }
}
